### ISSUE TITLE
Problem to get the version of the bootstrap go

### ISSUE THREAD

**Issue by simonfoilen** [echocat/gradle-golang-plugin#13]
Hi,

after the plugin downloads the go compiler, it tries to get the version, but it fails due to an unexisting folder.

```
12:33:40.168 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':docker-sudo:prepareToolchain'.
12:33:40.218 [ERROR] [org.echocat.gradle.plugins.golang.utils.Executor] go: cannot find GOROOT directory: /usr/local/go
12:33:40.218 [DEBUG] [org.echocat.gradle.plugins.golang.model.ToolchainSettings] Got unexpected exit code 2 while executing [/home/simon/.go/sdk/bootstrap/bin/go, version].
java.io.IOException: Got unexpected exit code 2 while executing [/home/simon/.go/sdk/bootstrap/bin/go, version].

Downloaded and extracted bootstrap to /home/simon/.go/sdk/bootstrap but it could not be validated as working go installation.
```

Executing myself the command fails as well:
```
$ /home/simon/.go/sdk/bootstrap/bin/go version
go: cannot find GOROOT directory: /usr/local/go
```

If I create the folder and then execute, it works:
```
$ sudo mkdir /usr/local/go
$ /home/simon/.go/sdk/bootstrap/bin/go version
go version go1.7.3 linux/amd64
```

thanks

**Comment by blaubaer** [comment]
Hi @provirus,

this sounds like #9 (which is already solved). Could you please do the following things:
1. Verify that you use the latest version of the gradle-golang-plugin. Minimum should be ``0.1.12`` - See [Plugin page](https://plugins.gradle.org/plugin/org.echocat.golang) for latest version.
2. If this is the latest version please paste at this issue the output of:
``gradle --stacktrace --info build``

Thank you!

**Comment by checketts** [comment]
I'm on OSX and ran into the same problems. It also allowed me to build once I did `sudo mkdir /usr/local/go` I was able to get past it.

Here is the termincal output: (ignore the funny unicode characters those are from my terminal's theme)
```
✘  ~/gocode/src/domo/prometheus-sidecar   master ●✚  gw build -s -i
Run Gradle /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/gradlew ...
Initialized native services in: /Users/clintchecketts/.gradle/native
Connected to daemon DaemonInfo{pid=62788, address=[1f29071a-db12-408b-9db1-37533b344d50 port:64697, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1480981310975, context=DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=d3fa630e-696b-46f8-a098-5f24d4f06909.1, currentDir=/Users/clintchecketts/gocode/src/domo/prometheus-sidecar}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@f99f5e0 from daemon DaemonInfo{pid=62788, address=[1f29071a-db12-408b-9db1-37533b344d50 port:64697, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1480981310975, context=DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 62788). The daemon log file: /Users/clintchecketts/.gradle/daemon/3.1/daemon-62788.out.log
Starting 6th build in daemon [uptime: 7 mins 10.757 secs, performance: 99%, no major garbage collections]
Executing build with daemon context: DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle'.
Included projects: [root project 'prometheus-sidecar']
Evaluating root project 'prometheus-sidecar' using build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle'.
Compiling build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle' using SubsetScriptTransformer.
Compiling build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle' using BuildScriptTransformer.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':baseValidate', task ':validate', task ':prepareToolchain', task ':baseGetTools', task ':getTools', task ':basePrepareSources', task ':prepareSources', task ':baseTest', task ':test', task ':baseBuild', task ':build']
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/fileHashes.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/fileSnapshots.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/taskArtifacts.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
:baseValidate (Thread[Daemon worker Thread 4,5,main]) started.
:baseValidate
Executing task ':baseValidate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Package:          github.com/my-user/my-project
Platforms:        linux-amd64, windows-amd64, darwin-amd64
Host:             darwin-amd64
Go version:       go1.7.4
GOROOT:           /Users/clintchecketts/.go/sdk/go1.7.4
GOROOT_BOOTSTRAP: /Users/clintchecketts/.go/sdk/bootstrap
GOPATH:           /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build/gopath
:baseValidate (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.003 secs.
:validate (Thread[Daemon worker Thread 4,5,main]) started.
:validate
Executing task ':validate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:validate (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.001 secs.
:prepareToolchain (Thread[Daemon worker Thread 4,5,main]) started.
:prepareToolchain
Executing task ':prepareToolchain' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
go: cannot find GOROOT directory: /usr/local/go
There was no go bootstrap found. Going to download it from https://storage.googleapis.com/golang/go1.7.4.darwin-amd64.tar.gz to /Users/clintchecketts/.go/sdk/bootstrap ...
go: cannot find GOROOT directory: /usr/local/go
:prepareToolchain FAILED
:prepareToolchain (Thread[Daemon worker Thread 4,5,main]) completed. Took 8.449 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareToolchain'.
> Downloaded and extracted bootstrap to /Users/clintchecketts/.go/sdk/bootstrap but it could not be validated as working go installation.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareToolchain'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:186)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:183)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.IllegalStateException: Downloaded and extracted bootstrap to /Users/clintchecketts/.go/sdk/bootstrap but it could not be validated as working go installation.
        at org.echocat.gradle.plugins.golang.tasks.PrepareToolchain.downloadBootstrapIfRequired(PrepareToolchain.java:241)
        at org.echocat.gradle.plugins.golang.tasks.PrepareToolchain.run(PrepareToolchain.java:42)
        at org.echocat.gradle.plugins.golang.tasks.GolangTaskSupport.runBare(GolangTaskSupport.java:99)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more


BUILD FAILED

Total time: 9.525 secs
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':prepareToolchain'.] from daemon DaemonInfo{pid=62788, address=[1f29071a-db12-408b-9db1-37533b344d50 port:64697, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1480981310975, context=DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
```

Ran the `mkdir` and tried again:
```
 ✘  ~/gocode/src/domo/prometheus-sidecar   master ●✚  sudo mkdir /usr/local/go
Password:
 ~/gocode/src/domo/prometheus-sidecar   master ●✚  gw build -s -i
Run Gradle /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/gradlew ...
Initialized native services in: /Users/clintchecketts/.gradle/native
Connected to daemon DaemonInfo{pid=62788, address=[1f29071a-db12-408b-9db1-37533b344d50 port:64697, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1480981377321, context=DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=7bc3b0ae-5253-465f-9c2d-57dab98885d0.1, currentDir=/Users/clintchecketts/gocode/src/domo/prometheus-sidecar}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@f99f5e0 from daemon DaemonInfo{pid=62788, address=[1f29071a-db12-408b-9db1-37533b344d50 port:64697, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1480981377321, context=DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 62788). The daemon log file: /Users/clintchecketts/.gradle/daemon/3.1/daemon-62788.out.log
Starting 7th build in daemon [uptime: 8 mins 53.669 secs, performance: 99%, no major garbage collections]
Executing build with daemon context: DefaultDaemonContext[uid=032aca57-fba2-412d-a8bb-82cf5cd17e83,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home,daemonRegistryDir=/Users/clintchecketts/.gradle/daemon,pid=62788,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle'.
Included projects: [root project 'prometheus-sidecar']
Evaluating root project 'prometheus-sidecar' using build file '/Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build.gradle'.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':baseValidate', task ':validate', task ':prepareToolchain', task ':baseGetTools', task ':getTools', task ':basePrepareSources', task ':prepareSources', task ':baseTest', task ':test', task ':baseBuild', task ':build']
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/fileHashes.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/fileSnapshots.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/.gradle/3.1/taskArtifacts/taskArtifacts.bin: Size{0}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
:baseValidate (Thread[Daemon worker Thread 5,5,main]) started.
:baseValidate
Executing task ':baseValidate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Package:          github.com/my-user/my-project
Platforms:        linux-amd64, windows-amd64, darwin-amd64
Host:             darwin-amd64
Go version:       go1.7.4
GOROOT:           /Users/clintchecketts/.go/sdk/go1.7.4
GOROOT_BOOTSTRAP: /Users/clintchecketts/.go/sdk/bootstrap
GOPATH:           /Users/clintchecketts/gocode/src/domo/prometheus-sidecar/build/gopath
:baseValidate (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.004 secs.
:validate (Thread[Daemon worker Thread 5,5,main]) started.
:validate
Executing task ':validate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:validate (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.001 secs.
:prepareToolchain (Thread[Daemon worker Thread 5,5,main]) started.
:prepareToolchain
Executing task ':prepareToolchain' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
There was no go SDK sources of version go1.7.4 found. Going to download it from https://storage.googleapis.com/golang/go1.7.4.src.tar.gz to /Users/clintchecketts/.go/sdk/go1.7.4 ...
Go toolchain sources (go1.7.4) successfully downloaded to "/Users/clintchecketts/.go/sdk/go1.7.4".
Going to build go toolchain for darwin-amd64...
Go toolchain for darwin-amd64 build.
Going to build go toolchain for linux-amd64...
Go toolchain for linux-amd64 build.
Going to build go toolchain for windows-amd64...
Go toolchain for windows-amd64 build.
Going to build tool importsExtractor...
Tool importsExtractor build.
:prepareToolchain (Thread[Daemon worker Thread 5,5,main]) completed. Took 2 mins 16.426 secs.
:baseGetTools (Thread[Daemon worker Thread 5,5,main]) started.
```
(snipped remaining output)

**Comment by blaubaer** [comment]
Hi @checketts!

Can you confirm that you use the lastest version of the ``gradle-golang-plugin`` (minimum ``0.1.12``) ?

**Comment by blaubaer** [comment]
Got no response for more than 2 weeks and I'am not able to reproduce it.
I will close it for now. If someone is able to reproduce it and can provide information requested above please reopen it.
Thank you!
